/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractSkeleton(code: string, ext: string): string

export declare function generateHeatmap(code: string, ext: string, cursorLine: number): string

export declare function getLocalImports(code: string, ext: string): Array<string>

export declare function indexWorkspace(directory: string): string

export declare function packContext(code: string, ext: string, maxTokens: number, cursorLine: number): string
